name: "ssh deploy"
description: 'auto deploy the container'

inputs:
  services_name:
    required: true
    type: string
    is-array: true

runs:
  using: "composite"
  steps:
    - name: Run production deploy script
      uses: appleboy/ssh-action@master
      with:
        host: 42.193.16.100
        username: ubuntu
        password: 87cca89@87CCA89
        script: |
          sudo -i
          cd /tmp
          echo "${{ inputs.services_name }}" >> services
          services_name=$(awk BEGIN{RS=EOF}'{gsub(/\n/," ");print}' services)
          docker compose pull $services_name
        command_timeout: 30m