name: "ssh deploy"
description: 'auto deploy the container'

inputs:
  services_name:
    required: true
    type: string
    is-array: true
  test:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ inputs.test }}, ${{ inputs.services_name }}"
    - name: Run production deploy script
      uses: appleboy/ssh-action@master
      with:
        host: 42.193.16.100
        port: 22
        username: root
        password: 87cca89@87CCA89
        script: |
          cd /tmp
          echo "${{ inputs.services_name }}" > services
          services_name=$(awk BEGIN{RS=EOF}'{gsub(/\n/," ");print}' services)
        command_timeout: 30m