name: "count file of directory"
description: 'get the file counts of directory and generated the matrix automatically'

inputs:
  path:
    description: "The directory which is the files you want to count"
    required: true

runs:
  using: "composite"
  steps:
    - name: Count files number
      shell: bash
      run: |
        pwd
        cd ${{ inputs.path }}
        count=$(ls -l | grep "^-" | wc -l)
        ls
        ls -l | grep "^-" | wc -l
        str="["
        for ((i=1; i<=8; i++))
        do
          if [[ $i -eq 1 ]] ;
            then
              str=$str$i;
            else
              str=$str', '$i;
          fi
        done
        str=$str"]"
        echo $str
        echo "::set-output name=dir_matrix::$str"