name: b

on: workflow_call

jobs:
  build:
    name: build backend go image
    runs-on: ubuntu-latest
    steps:
      - run: echo 'b running'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s