name: entrance

on: push

jobs:

  test:
    name: aww
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: setup docker and login
        uses: Charlotte-z/workflows/setup_docker@main
        with:
          registry: ghcr.io/geekrv/workflow
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - run: |
            echo ${{ github.sha }}
            echo ${{ steps.short-sha.outputs.sha }}
            echo '${{ toJSON(github.event.commits) }}'
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/geekrv/workflow:${{ env.TRIM_BRANCH }}.${{ steps.short-sha.outputs.sha }}

  # build-a:
  #   uses: ./.github/workflows/build-a.yml

  # build-b:
  #   uses: ./.github/workflows/build-b.yml

  # integration:
  #   needs: [build-b, build-a]
  #   uses: ./.github/workflows/test-integration.yml