# Pull nodejs image and mount admin-frontend as dev

name: Build admin frontend

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  merge_group:
    branches: [ main ]
  workflow_call:
    inputs:
      commit_sha:
        description: 'Commit SHA to checkout'
        required: true
        type: string

#2
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
    - name: log
      run: |
        echo "${{ inputs.commit_sha }}"
    
    - name: Trim branch
      uses: wikifactory/wikifactory-actions/trim_branch@main

    - name: check
      run: |
        echo "${{ env.TRIM_BRANCH }}"
        echo "${{ github.event_name }}"