name: a

on: workflow_call

jobs:
  build:
    name: build a test
    if: ${{ github. }}
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s