name: Trigger and Wait Workflow

on:
  push:

jobs:
  trigger-and-wait:
    runs-on: ubuntu-latest
    env:
      OWNER: "Charlotte-z"               # 设置环境变量
      REPO: "test-repo"                  # 设置环境变量
      WORKFLOW_FILE: "deploy.yml"       # 设置环境变量
    steps:
      - name: Trigger another repository's workflow and wait
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # 使用GitHub Secrets来引用PAT
        run: |
          trigger_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Triggering workflow at $trigger_time"

          # 触发workflow
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
            -d '{"event_type": "custom-event-name", "client_payload": {"environment": "sssss"}}'

          echo "Workflow triggered, waiting for it to start..."

          sleep 5

          should_exit=false

          while true; do
            runs=$(curl -s \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${OWNER}/${REPO}/actions/runs?per_page=5")

            while IFS= read -r line; do
              id=$(echo "$line" | jq -r '.id')
              created_at=$(echo "$line" | jq -r '.created_at')

              created_at_ts=$(date -u -d "$created_at" +%s)
              trigger_time_ts=$(date -u -d "$trigger_time" +%s)

              diff=$((created_at_ts - trigger_time_ts))
              
              if [ $diff -le 10 ] && [ $diff -ge -10 ]; then
                echo "Found matching workflow run: ID $id, Created at $created_at"
                should_exit=true
                break 2
              fi
            done < <(echo "$runs" | jq -c '.workflow_runs[] | select(.created_at > "'$trigger_time'")')

            if [ "$should_exit" = true ]; then
              break
            fi

            sleep 10
          done
