name: Entrance

on: push

jobs:
  is_wasm_changed:
    name: Detect file change
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'total object count: 4                   	total object sum size: 3768924' > a
          cat a | grep 'total object count: 4' > str || true
          if [ -s str ];then echo "is_build=false" >> $GITHUB_ENV; else echo "is_build=true" >> $GITHUB_ENV; fi
    outputs:
      is_build: ${{ env.is_build }}

  publish_staging:
    needs: [is_wasm_changed]
    if: needs.is_wasm_changed.outputs.is_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo '111'