name: a

on: workflow_call:

jobs:
  build:
    name: build a
    runs-on: ubuntu-latest
    only:
      changes:
        - "a/**.js"
    steps:
      - run: echo 'a is running'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s