name: test a

on: workflow_call

jobs:
  is_files_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo '${{ toJSON(github.event) }}'
      - uses: tj-actions/changed-files@v22
        id: filter
        with:
          files: |
              - 'a/**'
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}

  build:
    name: build a
    runs-on: ubuntu-latest
    needs: is_files_changed
    if: needs.is_files_changed.outputs.output1 == 'true'
    steps:
      - run: |
          echo 'flask_image=awddwawadwadawdawdwadaw' > test.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: test.txt
      - run: ${{ toJSON(needs.is_files_changed.outputs.output1) }}
      - run: echo 'a is running'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s