name: a

on: workflow_call

jobs:
  is_files_changed:
    uses: Charlotte-z/workflows/.github/workflows/path_filters@main
    with:
      filters: |
        'a/**'
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: dorny/paths-filter@v2
    #     id: filter
    #     with:
    #       filters: |
    #         workflows:
    #           - 'a/**'
    # outputs:
    #   output1: ${{ steps.filter.outputs.workflows }}

  build:
    name: build a
    runs-on: ubuntu-latest
    needs: is_files_changed
    if: needs.is_files_changed.outputs.output1 == 'true'
    steps:
      - run: ${{ toJSON(needs.is_files_changed.outputs.output1) }}
      - run: echo 'a is running'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s