name: Entrance

on: push

jobs:
  is_wasm_changed:
    name: Detect file change
    runs-on: ubuntu-latest
    steps:
      - uses: Charlotte-z/workflows/test@main
        id: t
      - run: echo "${{ steps.t.outputs.ots }}"