# Pull nodejs image and mount admin-frontend as dev

name: Build admin frontend

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  merge_group:
    branches: [ main ]
  workflow_call:

#2
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
    - name: Trim branch
      uses: wikifactory/wikifactory-actions/trim_branch@main

    - name: check
      run: |
        echo "${{ env.TRIM_BRANCH }}"