name: entrance

on:
  push:

jobs:
  delete_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clean GHCR packages
        uses: cresh-io/action-ghcr-batch-delete-versions@v1
        with:
          github-access-token: "${{ secrets.TOKEN }}"
          org: "geekrv"
          package_name: "workflow"
          package_type: "container"   # Default is container because the action was design only for containers at first
          selector: |
              type=tagCount;operator=greaterThan;value=0
              type=tags;operator=startsWith;value=test16.f9e6a51
          # excluder: |
          #     type=tags;operator=equals;value=pr-1-ee20adc
          dry-run: "0"
      # - run: |
      #     curl \
      #     -X DELETE \
      #     -H 'Authorization: Bearer ${{ secrets.TOKEN }}' \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     https://api.github.com/orgs/geekrv/packages/container/workflow/versions/106665013
      #https://api.github.com/users/USERNAME/packages/PACKAGE_TYPE/PACKAGE_NAME/versions/PACKAGE_VERSION_ID


# curl -i \
# -X DELETE \
# -H 'Authorization: Bearer ${{ secrets.TOKEN }}' \
# -H "Accept: application/vnd.github.v3+json" \
# https://api.github.com/geekrv/workflow/typescript-monorepo-example-main-internal-api/versions/

  # test:
  #   name: aww
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - uses: benjlevesque/short-sha@v1.2
  #       id: short-sha
  #     - name: ssss
  #       run: |
  #         echo '${{ toJSON(github) }}'
  #     - name: trim branch
  #       uses: Charlotte-z/workflows/trim_branch@main
  #     - name: setup docker and login
  #       uses: Charlotte-z/workflows/setup_docker@main
  #       with:
  #         registry: ghcr.io/geekrv/workflow
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.TOKEN }}
  #     - run: echo ${{ steps.short-sha.outputs.sha }}
  #     - name: Build image and push to GitHub Container Registry
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         push: true
  #         platforms: linux/amd64, linux/arm64
  #         tags: |
  #           ghcr.io/geekrv/workflow:${{ env.TRIM_BRANCH }}.${{ steps.short-sha.outputs.sha }}

  # build-a:
  #   uses: ./.github/workflows/build-a.yml

  # build-b:
  #   uses: ./.github/workflows/build-b.yml

  # integration:
  #   needs: [build-b, build-a]
  #   uses: ./.github/workflows/test-integration.yml