# Pull nodejs image and mount admin-frontend as dev

name: Build admin frontend

on:
  workflow_call:
    inputs:
      environment:
        description: 'manual publish to environment'
        required: false
        type: string


#2
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
    - name: log
      if: ${{ github.event_name == 'pull_request' || inputs.environment == 'staging' }}
      run: |
        echo "${{ inputs.commit_sha }}"

    - name: Trim branch
      uses: wikifactory/wikifactory-actions/trim_branch@main

    - name: check
      run: |
        echo "${{ env.TRIM_BRANCH }}"
        echo "${{ github.event_name }}"