name: a

on: workflow_call

jobs:
  build:
    name: build a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'a/**'

        # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: echo 'skiped'
      - run: echo 'a is running'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s