on:
  pull_request:
    types: [opened, synchronize]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create check run for ${{ github.sha }}
        uses: ./
        id: create_check_run
        with:
          route: POST /repos/${{ github.actor }}/workflows/check-runs
          owner: ${{ github.actor }}
          repo: workflows
          name: Test check run
          head_sha: ${{ github.sha }}
          output: |
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}