name: entrance

on: push

jobs:

  build-a:
    uses: ./.github/workflows/build-a.yml

  build-b:
    uses: ./.github/workflows/build-b.yml

  integration:
    needs: [build-b, build-a]
    uses: ./.github/workflows/test-integration.yml