name: Entrance

on: push

env:
  SERVICES_NAME: "nginx postgres node"

jobs:

  is_wasm_changed:
    name: Detect file change
    runs-on: ubuntu-latest
    steps:
      - name: Run production deploy script
        uses: appleboy/ssh-action@master
        with:
          host: 42.193.16.100
          port: 22
          username: root
          password: 87cca89@87CCA89
          script: |
            cd /tmp
            docker-compose pull ${{ env.SERVICES_NAME }}
          command_timeout: 30m