name: Entrance

on: push

jobs:

  is_wasm_changed:
    name: Detect file change
    runs-on: ubuntu-latest
    steps:
      - uses: Charlotte-z/workflows/ssh-deploy@main
        with:
          services_name:
            - postgres
            - redis
            - nodejs