on: 
  pull_request:
    types: [opened, synchronize]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
   
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Create check run for ${{ github.sha }}
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: Charlotte-z
          repo: workflows
          name: Test check run
          head_sha: ${{github.event.pull_request.head.sha}}
          output: |
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: update_check_run
        with:
          route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
          owner: Charlotte-z
          repo: workflows
          check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
          conclusion: "success"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}