name: Entrance

on: push

jobs:
  is_wasm_changed:
    name: Detect file change
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'total object count: 4                   	total object sum size: 3768924' > a
          cat a | grep 'total object count: 4' > str
          if [ -s str ];then echo ‘’; else echo 2; fi