name: a

on: workflow_call

jobs:
  build:
    name: build a
    runs-on: ubuntu-latest
    steps:
      - name: Verify Dockerfile changed
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
             a/**
      - if: steps.changed_files.outputs.files_changed == 'true'
        run: echo 'skiped'
      - run: echo 'a is running'
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s