name: entrance

on: push

jobs:
  is_dev_dependency_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker pull nginx
          docker image ls
          docker run --name nginx -p 80:80 -d nginx
          docker exec nginx mkdir -p /root/keys
          docker exec nginx openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /root/keys/private.pem -out cert.pem -pubkey -batch
          docker exec nginx openssl rsa -in /root/keys/private.pem -pubout > /root/keys/public.pem
          docker exec nginx mkdir -p /root/keys/public
          docker exec nginx chmod -R 777 /root/keys/public
          docker exec nginx chmod 777 /root/keys/public/public.pem
          docker exec nginx cp /root/keys/public.pem /root/keys/public/public.pem

  # test2:
  #   needs: is_dev_dependency_changed
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo done
  #   outputs:
  #     dev_changed: ${{ needs.is_dev_dependency_changed.outputs.file_changed }}

  # test3:
  #   needs: test2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         if ${{ needs.test2.outputs.dev_changed }};then export FLASK_IMAGE=development-env-test; else export FLASK_IMAGE=development-env; fi





  # workflow-a:
  #   uses: ./.github/workflows/workflow-a.yml
  #   secrets: inherit

  # integration:
  #   needs: [workflow-a]
  #   # if: needs.workflow-a.result == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "${{ toJSON(needs.workflow-a.conclusion) }}"
