name: entrance

on: push

# build jobs will only run when the PR is not in draft mode
jobs:
  build_ingress_dev:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/test/workflow-a.yml
    secrets: inherit

  # run integration test when all the build finished
  integration:
    needs: [build_ingress_dev]
    # for now meet some trouble
    # if: needs.build_backend_go.result == 'success' && needs.build_flask.result == 'success' && needs.build_frontend_dev.result == 'success' && needs.build_ingress_dev.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'

