name: entrance

on: push

jobs:
  is_dev_dependency_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tj-actions/changed-files@v22
        id: filter
        with:
          files: |
              src/**
    outputs:
      file_changed: ${{ steps.filter.outputs.any_changed }}

  test2:
    needs: is_dev_dependency_changed
    runs-on: ubuntu-latest
    steps:
      - run: echo done
    outputs:
      dev_changed: needs.is_dev_dependency_changed.outputs.file_changed

  test3:
    needs: test2
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.test2.outputs.dev_changed }}
  # workflow-a:
  #   uses: ./.github/workflows/workflow-a.yml
  #   secrets: inherit

  # integration:
  #   needs: [workflow-a]
  #   # if: needs.workflow-a.result == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "${{ toJSON(needs.workflow-a.conclusion) }}"
