name: entrance

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  is_dev_dependency_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker image build --tag t .
          docker run t
          docker ps

  # test2:
  #   needs: is_dev_dependency_changed
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo done
  #   outputs:
  #     dev_changed: ${{ needs.is_dev_dependency_changed.outputs.file_changed }}

  # test3:
  #   needs: test2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         if ${{ needs.test2.outputs.dev_changed }};then export FLASK_IMAGE=development-env-test; else export FLASK_IMAGE=development-env; fi





  # workflow-a:
  #   uses: ./.github/workflows/workflow-a.yml
  #   secrets: inherit

  # integration:
  #   needs: [workflow-a]
  #   # if: needs.workflow-a.result == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "${{ toJSON(needs.workflow-a.conclusion) }}"
