name: entrance

on: push

jobs:
  is_dev_dependency_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker image build --tag t .
          docker run t
          docker ps
          docker exec t mkdir -p ~/keys
          docker exec t openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout ~/keys/private.pem -out cert.pem -pubkey -batch
          docker exec t openssl rsa -in ~/keys/private.pem -pubout > ~/keys/public.pem
          docker exec t mkdir -p ~/keys/public
          docker exec t cp ~/keys/public.pem ~/keys/public/public.pem

  # test2:
  #   needs: is_dev_dependency_changed
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo done
  #   outputs:
  #     dev_changed: ${{ needs.is_dev_dependency_changed.outputs.file_changed }}

  # test3:
  #   needs: test2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         if ${{ needs.test2.outputs.dev_changed }};then export FLASK_IMAGE=development-env-test; else export FLASK_IMAGE=development-env; fi





  # workflow-a:
  #   uses: ./.github/workflows/workflow-a.yml
  #   secrets: inherit

  # integration:
  #   needs: [workflow-a]
  #   # if: needs.workflow-a.result == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "${{ toJSON(needs.workflow-a.conclusion) }}"
