name: entrance

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    outputs:
      file_changed: true

  test2:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs.file_changed
    steps:
      - run: |
          echo ${{ needs.test.outputs.file_changed }}
          if ${{ needs.test.outputs.file_changed }};then export FLASK_IMAGE=development-env-222; else export FLASK_IMAGE=development-env; fi
          export

  test3:
    needs: test2
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo  done
  # workflow-a:
  #   uses: ./.github/workflows/workflow-a.yml
  #   secrets: inherit

  # integration:
  #   needs: [workflow-a]
  #   # if: needs.workflow-a.result == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "${{ toJSON(needs.workflow-a.conclusion) }}"
