name: run-integration

on:
  workflow_call:
    inputs:
      A:
        required: false
        type: string
        default: master

jobs:
  build:
    name: run docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          touch .env
          echo A=${{ inputs.A }} >> .env
          docker-compose up -d