name: run-integration

on:
  workflow_run:
    workflows: [a, b]
    types:
      - completed

jobs:
  build:
    name: run docker compose
    runs-on: ubuntu-latest
    steps:
      - run: echo "integration"