name: Manual Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: A
        run: ls

      - name: Test
        id: package-version-update
        uses: Charlotte-z/workflows/increase_version@main
        with:
          path: ./package.json

      - name: Check
        run: |
          cat package.json

      - name: Show old and new version
        run: |
          echo "Old Version: ${{ steps.package-version-update.outputs.old-version }}"
          echo "New Version: ${{ steps.package-version-update.outputs.new-version }}"

      - name: Commit to master
        run: |
          git config --local user.email '2698028166@qq.com'
          git config --local user.name "Charlotte-z"
          git add -A
          git commit -am'update version from ${{ steps.package-version-update.outputs.old-version }} to ${{ steps.package-version-update.outputs.new-version}}'
          git push origin main
