name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to which environment'
        required: true
        default: 'canary'
        type: choice
        options:
        - canary
      frontend:
        description: 'Deploy frontend'
        required: false
        type: boolean
        default: true
      backend_flask:
        description: 'Deploy backend flask'
        required: false
        type: boolean
        default: true
      celery:
        description: 'Deploy celery'
        required: false
        type: boolean
        default: true
      backend_go:
        description: 'Deploy backend_go'
        required: false
        type: boolean
        default: true