name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo tag
        run: echo ${{ github.event.inputs.tag }}
