name: Update version in package.json

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Release to environment"
        required: true
        default: "warning"
        type: choice
        options:
          - staging


jobs:
  test:
    needs: update-version
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ github.event.inputs.environment }}