name: Update version in package.json

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.2.3)'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq

      - name: Update version in package.json
        run: |
          jq '.version = "${{ github.event.inputs.version }}"' package.json > tmp.json && mv tmp.json package.json

      - name: Commit to master
        run: |
          git config --local user.email '2698028166@qq.com'
          git config --local user.name "Charlotte-z"
          git add -A
          git commit -am'update version from ${{ github.event.inputs.version }}'
          git push origin main
