name: Test

on:
  push
  release:
    types: [published]
  pull_request:
    types:
      - closed
      

jobs:
  deploy_wasm:
    name: Deploy wasm to staging
    uses: ./.github/workflows/other2.yml
    secrets: inherit

  one:
    runs-on: ubuntu-latest
    needs: deploy_wasm
    steps:
      - run: |
          echo "${{ toJSON(github.event_name) }}"
      - name: test
        if: github.event_name == 'push'
        run: echo "test"