name: Test

on:
  push:
  release:
    types: [published]
  pull_request:
    types:
      - closed
      

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "is_staging=false" >> $GITHUB_ENV;
          echo "is_production=true" >> $GITHUB_ENV;
      - name: test
        if: ${{ env.is_staging }}
        run: echo "test"