name: Test

on: push

jobs:
  one:
    strategy:
      matrix:
        include:
          - environment: production
          - environment: staging
          - environment: dev
    environment:
      name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ vars.ENV }}"