name: Test

on:
  push:
  release:
    types: [published]
  pull_request:
    types:
      - closed
      

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github.event_name) }}"
          echo "${{ github.event_name == "pushj" }}"
      - name: test
        # if: ${{ github.event_name == "pushj"}}
        run: echo "test"