name: Test

on: push

jobs:
  deploy_wasm:
    name: Deploy wasm to staging
    uses: ./.github/workflows/other2.yml
    secrets: inherit

  one:
    runs-on: ubuntu-latest
    needs: deploy_wasm
    steps:
      - run: |
          echo "${{ toJSON(github.event_name) }}"