name: Test

on:
  push:
  release:
    types: [released]
  pull_request:
    types:
      - closed


jobs:
  one:
    uses: ./.github/workflows/other2.yml
  
  two:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "workflow triggered!"
  # preset:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         en=ww
  #         if [[ "${{ github.event_name }}" == 'push' ]]; then
  #           echo "environment=production" >> $GITHUB_ENV;
  #         fi
  #   outputs:
  #     environment: ${{ env.environment }}

  # one:
  #   runs-on: ubuntu-latest
  #   needs: preset
  #   environment: ${{ needs.preset.outputs.environment }}
  #   steps:
  #     - run: |
  #         echo "${{ vars.ENV }}"