name: Test

on: push

jobs:
  one:
    environment:
      name: ${{ github.event.deployment.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.deployment.environment }}"