name: Release backend_go to prod

on:
  workflow_call:

jobs:
  publish-production:
    runs-on: ubuntu-latest
    name: Publish production
    steps:
      - run: echo "is:${{ toJSON(github.event_name) }}"
