name: "output is file changed"
description: 'simplify file change action'

on:
  workflow_call:
    inputs:
      filters:
        description: 'Path to the configuration file or YAML string with filters definition'
        required: true


jobs:
  is_files_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ${{ inputs.filters }}
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}