on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: Search latest semver Image
        uses: tinact/docker.image-retag@master
        with:
          image_name: workflow
          image_old_tag: test
          image_new_tag: tagtest
          registry: ghcr.io/geekrv
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}