on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: Retag to prod
        uses: kindaninja/retag-image-ghcr@0.1.0
        with:
          registry: ghcr.io/geekrv
          image: workflow
          current_tag: test
          new_tag: v42-prod
          username: github
          password: ${{ secrets.GITHUB_TOKEN }}