name: Release to prod

on:
  release:
    types: [published]

jobs:
  publish-production:
    runs-on: ubuntu-latest
    name: Publish production
    steps:
      - run: if [ -n "$run" ];then echo "changed=true" >> $GITHUB_ENV; else echo "changed=false" >> $GITHUB_ENV; fi
      - run: echo ${{ env.changed }}