on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/geekrv
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
        - name: Search latest semver Image
          uses: tinact/docker.image-retag@master
          with:
            image_name: workflow
            image_old_tag: test
            image_new_tag: tt2
            registry: ghcr.io/geekrv/workflow
            registry_username: ${{ github.actor }}
            registry_password: ${{ secrets.TOKEN }}