name: Staging Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  is_files_changed:
    name: Detect file change
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tj-actions/changed-files@v22
        id: filter
        with:
          files: |
              backend_go/**
    outputs:
      file_changed: ${{ steps.filter.outputs.any_changed }}

  echo:
    runs-on: ubuntu-latest
    needs:
      - is_files_changed
    name: success
    steps:
      - run: echo ${{ needs.is_files_changed.outputs.file_changed }}