name: Release to prod

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Build dev flask
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            docker pull ghcr.io/geekrv/workflow:test123