on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: Add Semantic Version tag to Docker Image
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: ghcr.io/geekrv
          repository: workflow
          target: test
          tags: lalala
      # - name: Retag to prod
      #   uses: kindaninja/retag-image-ghcr@0.1.0
      #   with:
      #     registry: ghcr.io/geekrv
      #     image: workflow
      #     current_tag: test
      #     new_tag: v42-prod
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.TOKEN }}