on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: Retag to latest
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ghcr.io/geekrv
          name: my-awesome-docker-image/my-package
          old_tag: test
          new_tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}