on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/geekrv
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Retag to latest
        uses: Z-M-Huang/docker-retag-curl@0.1.0
        with:
          repo: ghcr.io/geekrv/workflow
          old_tag: test
          new_tag: ss
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}