on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      # - name: trim branch
      #   uses: Charlotte-z/workflows/trim_branch@main
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/geekrv
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/geekrv/workflow:test
          dst: |
            ghcr.io/geekrv/workflow:test222222222
      - name: Delete image
        uses: chipkent/action-cleanup-package@v1.0.1
        with:
          # NOTE: at now only orgs is supported
          package-name: geekrv/workflow
          # NOTE: using Personal Access Token
          github-token: ${{ secrets.TOKEN }}
          tag: test
      # - name: Retag to prod
      #   uses: kindaninja/retag-image-ghcr@0.1.0
      #   with:
      #     registry: ghcr.io/geekrv
      #     image: workflow
      #     current_tag: test
      #     new_tag: v42-prod
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.TOKEN }}