name: Staging Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  echo:
    runs-on: ubuntu-latest
    name: success
    steps:
      - name: Output Run ID
        run: |
          echo ${{ github.event.pull_request.number }}