name: Release to prod

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup docker and login
        uses: Charlotte-z/workflows/setup_docker@main
        with:
          registry: ghcr.io/geekrv/workflow
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build dev flask
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/geekrv/workflow:branch3
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Retag master
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/geekrv/workflow:branch3
          dst: |
            ghcr.io/geekrv/workflow:master.${{ steps.short-sha.outputs.sha }}
            ghcr.io/geekrv/workflow:master