on:
  pull_request:
    types:
      - closed
#ssssssss
jobs:
  test:
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Charlotte-z/workflows/pr_commit_sha@main
      - run: echo '${{ toJSON(github) }}'
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/geekrv
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - uses: Charlotte-z/workflows/pr_commit_sha@main
      - run: echo ${{ env.LAST_ONE_SHA }}
      - name: Push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/geekrv/workflow:${{ github.event.pull_request.head.ref }}.${{ env.last_one_commit_sha }}
          dst: |
            ghcr.io/geekrv/workflow:main.${{ steps.short-sha.outputs.sha }}

      # - name: Search latest semver Image
      #   uses: tinact/docker.image-retag@master
      #   with:
      #     image_name: workflow
      #     image_old_tag: test
      #     image_new_tag: hahaha
      #     registry: ghcr.io/geekrv
      #     registry_username: ${{ github.actor }}
      #     registry_password: ${{ secrets.TOKEN }}
      # - name: Delete image
      #   uses: bots-house/ghcr-delete-image-action@v1.0.0
      #   with:
      #     # NOTE: at now only orgs is supported
      #     owner: geekrv
      #     name: workflow
      #     # NOTE: using Personal Access Token
      #     token: ${{ secrets.TOKEN }}
      #     tag: test
      # - name: Delete image
      #   uses: chipkent/action-cleanup-package@v1.0.1
      #   with:
      #     # NOTE: at now only orgs is supported
      #     package-name: geekrv/workflow
      #     # NOTE: using Personal Access Token
      #     github-token: ${{ secrets.TOKEN }}
      #     tag: test

      # - name: Retag to prod
      #   uses: kindaninja/retag-image-ghcr@0.1.0
      #   with:
      #     registry: ghcr.io/geekrv
      #     image: workflow
      #     current_tag: test
      #     new_tag: v42-prod
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.TOKEN }}