on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: whatever
    steps:
      - name: trim branch
        uses: Charlotte-z/workflows/trim_branch@main
      - name: Login ghcr
        uses: ghcr.io/geekrv
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/geekrv/workflow:test
          dst: |
            ghcr.io/geekrv/workflow:test2