name: "setup docker"
description: 'reuse the same steps for docker'

inputs:
  username:
    description: "username for login ghcr.io"
    required: true
  password:
    description: "password or token for login ghcr.io"
    required: true

runs:
  using: "composite"
  steps:
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io/wikifactory/frontend
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2