name: Frontend e2e test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch tmp.txt

          if [ "${{ github.event_name }}" == "workflow_dispatch" ]
          then 
            cat <<EOT > tmp.txt
            ${{ github.commit.message }}
            EOT
            tmp_string=$(cat tmp.txt | tr '\n' "  ")
          else
            a='awddwaawd'
            cat <<EOT > tmp.txt
            123321
            EOT
            tmp_string=$(cat tmp.txt | tr '\n' "  ")
          fi

          echo "$tmp_string"