name: test a

on: workflow_call

jobs:
  build:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: homework
      - run: cat test.txt