name: Frontend e2e test

on: push


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Backup old services and deploy new services
        uses: appleboy/ssh-action@master
        env:
          DGRAPH_ADDR: awd
        with:
          host: 43.136.131.46
          username: ubuntu
          password: 87cca89@87CCA89
          envs: DGRAPH_ADDR
          script_stop: true
          script: |
            cd /tmp
            if [ "$DGRAPH_ADDR" = "awd" ]; then
              echo "1"
              echo "2"
              echo "3"
            fi

            if [ "$data" = "xxx" ]; then
              echo "4"
              echo "5"
              echo "6"
            fi