name: build-backend-go

on: push

jobs:
  build:
    name: build backend go image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "TRIM_BRANCH=$(echo ${{ github.ref_name }} | sed -r 's,/,-,g' | tr A-Z a-z)" >> $GITHUB_ENV

  integration:
    needs: build
    uses: ./.github/workflows/integration.yml
    with:
      A: ${{ env.TRIM_BRANCH }}
    secrets: inherit