name: run-integration

on: push
# on:
#   workflow_call:
#     inputs:
#       username:
#         required: true
#         type: string
#       registry:
#         required: true
#         type: string

jobs:
  build:
    name: run docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the stack
        run: |
          netstat -ntlp
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3