name: run-integration

on: push

jobs:
  build-a:
    uses:
      ./.github/workflows/build-a.yml
      dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'a/**'

  build-b:
    uses: ./.github/workflows/build-b.yml

  integration:
    needs: [build-b, build-a]
    name: run integration
    runs-on: ubuntu-latest
    steps:
      - run: echo "run after a, b, and integration"