name: Frontend e2e test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alpha code
        uses: actions/checkout@v3