name: Frontend e2e test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: echo "${{ steps.extract_branch.outputs.branch_name }}"