name: run-integration

on: push
# on:
#   workflow_call:
#     inputs:
#       username:
#         required: true
#         type: string
#       registry:
#         required: true
#         type: string

jobs:
  build:
    name: run docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: add host
        run: echo "127.0.0.1 localweb" | sudo tee -a /etc/hosts
      - name: Build the stack
        run: |
          docker-compose up -d
          curl http://localweb:8089
      - name:
        run: echo 'code pass'
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3