name: Frontend e2e test

on:
  push:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alpha code
        uses: actions/checkout@v3

      - uses: Charlotte-z/workflows/dir_count@main
        id: d
        with:
          path: .
      - run: echo ${{ steps.d.outputs.MX }}
    outputs:
      version_matrix: ${{ steps.d.outputs.MX }}
  
  two:
    runs-on: ubuntu-latest
    needs: [one]
    steps:
      - run: echo ${{ needs.one.outputs.version_matrix }}