name: Frontend e2e test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo "${{ steps.extract_branch.outputs.branch }}"