name: Frontend e2e test

on:
  workflow_call:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alpha code
        uses: actions/checkout@v3

      - uses: Charlotte-z/workflows/dir_count@main
        with:
          path: .
        id: t
      
      - run: echo ${{ t.outputs.dir_matrix }}