name: Frontend e2e test

on: push


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Backup old services and deploy new services
        uses: appleboy/ssh-action@master
        with:
          host: 42.193.16.100
          username: root
          password: 87cca89@87CCA89
          envs: DGRAPH_ADDR
          script_stop: true
          script: |
            echo 123