name: build backend go

on:
  workflow_call:

jobs:
  is_files_changed:
    runs-on: ubuntu-latest
    steps:
      - name: Login ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/geekrv
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/geekrv/workflow:aaa
      # - name: Push image
      #   uses: akhilerm/tag-push-action@v2.0.0
      #   with:
      #     src: ghcr.io/geekrv/workflow:retag
      #     dst: |
      #       ghcr.io/geekrv/workflow:main.b36572a