name: build backend go

on:
  workflow_call:

jobs:
  is_files_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            all:
              - 'src/**'
            b:
              - 'src/b.txt'
            a:
              - 'src/a.txt'
      - run: |
          echo ${{ steps.filter.outputs.all }}
          echo ${{ steps.filter.outputs.a }}
          echo ${{ steps.filter.outputs.b }}