name: build backend go

on:
  workflow_call:

jobs:
  is_files_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tj-actions/changed-files@v22
        id: filter
        with:
          files: |
              src/**
    outputs:
      file_changed: ${{ steps.filter.outputs.any_changed }}