name: build backend go

on:
  workflow_call:

jobs:
  is_files_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
      - run: |
          echo ${{ steps.filter.outputs.any_changed }}